on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: npm
      - name: Install
        run: npm install
      - name: Compile Typescript
        run: npx tsc
      - name: Webpack Compile
        run: npx webpack --config webpack.config.cjs
      - name: Run Node
        run: node public/main.cjs --ext .js,.ts      
      - name: Install Pipet-cli
        run: npm install -D pipet-cli
      - name: Run Pipet-cli
        run: npx pipet --ext .js,.ts
