on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: npm
      - name: Install Pipet-cli
        run: npm install -D pipet-cli
      - name: Run Pipet-cli
        run: npx pipet      